### ISSUE TITLE
HLS CMAF Profile Reference

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#10]
The existing reference for mapping CMAF to HLS can be found at: https://developer.apple.com/documentation/avfoundation/media_assets_playback_and_editing/about_the_common_media_application_format_with_http_live_streaming

Should this be sited normatively or informatively as it is not part of an official standards registry?

**Comment by technogeek00** [comment]
Our specification will rely on this text as an official reference, there is normative language ("should"). Krasmir to confirm with team that this should be considered the normative reference.

**Comment by krasimirkolarov** [comment]
As I also mentioned on the call back in June, this document is the best guidance for authoring CMAF content with HLS for Apple’s ecosystem. That said , it is not at a level of spec, i.e. things might change based on significant feedback from partners and user deploying the solution. The IETF spec is the normative document for the spec.

**Comment by mbergman42** [comment]
@krasimirkolarov, should there be a normative version of this (DASH-HLS) interop spec?

**Comment by technogeek00** [comment]
Based on Apple's feedback this will remain an informative document and we will reference it as such. From a packaging perspective the majority of the constraints we need to observe reside in the main rfc-8216bis specification and should we find inconsistencies we will take them back to Apple

**Comment by krasimirkolarov** [comment]
Sounds good
