### ISSUE TITLE
DASH CMAF Profile - Informational Questions

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#12]
Two open questions to Thomas (or other DASH experts):
- The CMAF Profile describes Self-Initializing Segments as a subset of segment types, but the description appears to align with a single file track that uses byte addressing. Is this correct and the correct terminology?
- Does the DASH profile require single CMAF Fragments per segment? My read has this possibly implying but not requiring depending on the scenario (`SegmentTemplate` vs `SegmentTimeline`)

**Comment by haudiobe** [comment]
_The CMAF Profile describes Self-Initializing Segments as a subset of segment types, but the description appears to align with a single file track that uses byte addressing. Is this correct and the correct terminology?_

This is correct.

_Does the DASH profile require single CMAF Fragments per segment? My read has this possibly implying but not requiring depending on the scenario (SegmentTemplate vs SegmentTimeline)_

No it does not. But there is some detailed discussion around this in the v5 draft for DASH-IF. I can provide some details.

**Comment by technogeek00** [comment]
Cleaning up long-standing comment, thanks for the information Thomas!
