### ISSUE TITLE
Basic Live Stream

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#17]
### Use Case Description
A single in the clear CMAF presentation that is being made available in real time

### Working Notes
- Requirements / restrictions are the same as segmented VOD presentations
- The only difference is the playout mechanism which is _mostly_ not related to the authoring

### Open Questions
- Should we combine VOD and LIVE basic presentations into single "Basic CMAF Presentation"?
- Are there constraints on segment duration / bitrate fluctuation that apply to both cases?

**Comment by technogeek00** [comment]
August 26th Meeting:
- Agree the simple presentation cases are very similar and could be combined
  - Complexity and difference in constraints for VOD vs LIVE will likely appear in other use cases such as Ad Insertion
- DASH has a 50% segment fluctuation restriction, HLS specification has no restriction, but HLS authoring guidelines for Apple devices provide a restriction.
   - Identified Question: How do we treat the HLS authoring guidelines for Apple Devices relative to format interop?

**Comment by krasimirkolarov** [comment]
If we would like interop to include Apple devices, the CMAF guidelines should includes the Apple ones (at least the MUST ones).

**Comment by technogeek00** [comment]
From experience I would also posit that the common restrictions for segment authoring requirements on Apple devices have become the defacto standard for HLS authored content as well necessitating their inclusions as a form of restriction here.

**Comment by technogeek00** [comment]
Properly reading the DASH 4th edition comment clarifies that any excessive duration fluctuation requires `SegmentTimeline` signalling. Relevant paragraph from 7.2.1 in 4th Edition
> In case the `@duration` attribute is used for the signalling of the duration of Segments, then the MPD
start times as defined in subclause 5.3.9.5.3 should provide an approximation of the Media Presentation
time TM within the Period. Specifically, the difference between MPD start time and presentation time TP
shall not exceed 50% of value of `@duration` divided by the value of the `@timescale` attribute. In case
the Segment Timeline is used for the signalling of the duration of Segments, then the MPD start times as
defined in subclause 5.3.9.5.3 shall provide exactly the Media Presentation time T M within the Period, i.e.
the MPD start time is the earliest presentation time of the Segment.

Based on this there are no direct restrictions in DASH or HLS for segment duration or bitrate fluctuation meaning we should omit them from segment authoring guidelines.

We could have an additional note that restrictive device profiles exist with relevant links though if the group feels strongly about this.

**Comment by technogeek00** [comment]
9/9 Meeting - Left for implementation by @technogeek00. Information that is relevant for authoring but a non-normative requirement can be detailed as additional informational constraints on the presentation.

**Comment by technogeek00** [comment]
Implementation:
- Merged live into regular case
- Segment bit rate constraint information SHOULD's added to primary authoring constraints section

Open to review

**Comment by technogeek00** [comment]
Implemented in first published document
