### ISSUE TITLE
Encrypted Media Presentation

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#19]
### Use Case Description
A single CMAF presentation that contains one or more protected switching sets

### Working Notes
- HLS Constraints
  - Segments can only have one encryption method with one key and IV
  - SAMPLE-AES encryption method, fMP4s protected with cbcs scheme of Common Encryption
  - IV may be present (ignored by FPS scheme)
- DASH Constraints
  - CMAF profile constraints on Adaptation Sets:
    - General alignment to Clause 8 of CMAF
    - Must have a **`ContentProtection`** element with `@schemeIdUri` equal to `"urn:mpeg:dash:mp4protection:2011"` where `@value` is the encryption scheme used and if `@cenc:default_KID` present must equal `tenc` box `default_KID`.
    - At least one **`ContentProtection`** element with system specific UUID, if `@cenc:default_KID` present must match `tenc` box `default_KID` and `cenc:pssh` element must match `moov` box `pssh`.
- CMAF Section 8 General Notes
  - Recommends manifest signaling of PSSH, not CMAF header
  - Box Notes
    - `senc` recommended, but any valid alternative boxes allowed
    - `saio` points to single contiguous entry `aux_info_type = cenc` if it exists using fragment relative addressing
    - `saiz` present only for subsample encryption
    - `saio`, `saiz`, `senc` omitable for constant ivs with no subsampling
    - `pssh` general not allowed in CMAF headers, exception cases given
  - Encryption Constraints
    - IVs for `cenc` scheme limited to 8-bytes
    - All tracks in switching set use the same `default_KID` and key value
    - NAL structured video track headers must be left unencrypted using subsample encryption
    - Video VCL data protected by subsample encryption with `bytesOfProtectedData` spanning all complete 16-byte blocks in the VCL slice data
    - `cenc` scheme `bytesOfProtectedData` shall be multiple of 16 bytes
    - `cbcs` `bytesOfProtectedData` shall start on the first complete byte of video data following the slice header and end on the end of the last complete 16-byte block of slice data in the video nal
- CMAF Section A1 Notes
   - CMFHD presentation profile (`"“urn:mpeg:cmaf:presentation_profile:cmfhd:2017"`) - in the clear
   - CMFHDc presentation profile (`"“urn:mpeg:cmaf:presentation_profile:cmfhdc:2017”"`) - cenc scheme
   - CMFHDs presentation profile (`"urn:mpeg:cmaf:presentation_profile:cmfhds:2017"`) - cbcs scheme
   - Manifests may signal both CMFHDc and CMFHDs if both `cenc` and `cbcs` encrypted variants of switching sets are available
- Undocumented common requirements
  - `cbcs` encrypt:skip pattern must be `1:9` for video
    - CSTF Issue: https://github.com/cta-wave/content-specification-task-force/issues/39
    - Deeper Reference: https://github.com/WICG/encrypted-media-encryption-scheme/issues/7
    - Note this conversation calls out `10:0` requirement for audio, but this is already explicitly required by CENC: "Tracks other than video are protected using whole-block full-sample encryption as specified in 9.7 and hence skip_byte_block SHALL be 0."
  - Sample auxiliary information required by most media engines, `saio` must properly point if present
    - No reference issue, but interesting conversation occurred in video-dev around stream with defined `senc` box and incorrectly written `saio` boxes, where playback worked in one browser but not another
  - IVs must be 16-bytes for `cbcs` scheme
    - Zero padding of 8-byte IVs is technically only defined as part of per sample IVs in CENC
    - The unspecified nature of 8-byte IVs have lead to implementation mismatch, some expect only 16-bytes, others will pad least significant bits with zeros

### Open Questions
- Are there other undocumented common constraints that others may know of?
- Based on deployment observations, should it be mandated that if a sample auxiliary box is present it is addressed by an `saio`?
- `cbcs` scheme must be used for interop, do we mandate only `cbcs` or allow `cenc` such that all `cenc` switching sets have equivalent `cbcs` ones?

### Potential Feedback Points
- DASH CMAF Profile and CMAF Section 8 conflict in description of `pssh` boxes as CMAF suggests only providing in the manifest but the manifest profile mandates alignment with header `pssh` box.
- `cbcs` scheme under-specification of IV size should be corrected in CENC

**Comment by technogeek00** [comment]
Breaking encryption key rotation out to a separate discussion set: https://github.com/cta-wave/dash-hls/issues/20

**Comment by mp4allday** [comment]
> * `cbcs` scheme must be used for interop, do we mandate only `cbcs` or allow `cenc` such that all `cenc` switching sets have equivalent `cbcs` ones?

Since `cbcs` is the default moving forward and that `cenc` does not bring additional functionality there is no need to carry multiple switching sets of the same content.

**Comment by technogeek00** [comment]
@mp4allday we will be defining `cbcs` as the mode required for interop support, but will highlight the additional market addressment and reasons that an operator may still choose to provide / produce `cenc` as well.

**Comment by technogeek00** [comment]
10/21 Call, Feedback review from Laurent:
- Handling consistency of non-video/audio tracks encryption: i.e. captions/metadata/image/thumbnail
- encrypt:skip pattern restriction is overly restrictive from forward looking perspective, restricting to be specified for underspecified media profiles
- Secondary item to specify target media profiles for this spec #23 
- In-segment single sample encryption format restriction text underspecified, John Simmons to confirm if CMAF does restrict, if it does we will remove the line, if not we will better specify
- 8-byte IV SHALL for `cenc` adjusted to reference CMAF instead of duplicating it
- `cenc` and `cbcs` encryption key sharing statement removed, security concern not interop

**Comment by technogeek00** [comment]
Implemented in first publication edition
