### ISSUE TITLE
Encryption Key Rotation

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#20]
### Use Case Description ###
Changing of the encryption key within a single CMAF track

### Working Notes ###
- Identified as part of early DRM general investigations (#19) but substantive enough to warrant independent addressment
- Two common methods of acquiring changed keys
  - Full License Rotation
  - Root/Leaf License Rotation
- Signaling compatibility may be driven by common DRM implementations

### Open Questions ###
- What is the industry best practice for each major DRM system?
- What is the industry best practice for HLS signaling?
- What is the industry best practice for DASH signaling?

**Comment by technogeek00** [comment]
Apple has kindly provided feedback on a series of HLS / Fairplay questions, which provides the following summary points

### HLS signaling requirements
- EXT-X-KEY always signaled before key changes in a stream
- EXT-X-SESSION-KEY used in master to prefetch keys on entry only
- EXT-X-DATERANGE can be utilized to forward signal key change in variants (_common scheme would need to be defined for specification to recommend this method_)
- Only full license retrieval flows are supported currently

### HLS effects on CMAF
- Segments SHALL only have one encryption key utilized for all contained samples
- Change of `default_KID` or usage of sample group will work
   - `default_KID` may have broader compatibility
   - Implication of `default_KID` change is new initialization segment, not a possibility for a single CMAF presentation currently

**Comment by technogeek00** [comment]
Previous interoperability conversations between CTA-WAVE CSTF and DASH-IF CPS have identified the following notable points:
- `default_KID` changes are most interoperable and will work with all DRM systems
   - Forces DASH Period change
- Sample group possible but needs deeper interoperability investigation
- Key Hierarchy structures solve use case and scalability concerns, but requires both sample group support and usage of an embedded PSSH (or PSSH like) structure

**Comment by billmay** [comment]
questions about HLS effects on CMAF: change of default_KID would cause a new EXT-X-MAP statement; does this imply that a EXT-X-DISCONTINUITY must be used?

**Comment by billmay** [comment]
Another question about HLS/Fairplay: what is the best way to signal the new IV?  The IV is not required with SAMPLE-AES encryption.  The IV is normally set in the tenc box, which would be from the EXT-X-MAP.

**Comment by RufaelDev** [comment]
@billmay probably, as you know the seig box contains the signalling for the IV see cenc: 

```
aligned(8) class CencSampleEncryptionInformationGroupEntry
	extends SampleGroupEntry( ‘seig’ )
{
	unsigned int(8)		reserved = 0;
	unsigned int(4)		crypt_byte_block = 0;
	unsigned int(4)		skip_byte_block = 0;
	unsigned int(8)		isProtected;
	unsigned int(8)		Per_Sample_IV_Size;
	unsigned int(8)[16]	KID;
	if (isProtected ==1 && Per_Sample_IV_Size == 0) {
		unsigned int(8)	constant_IV_size;
		unsigned int(8)[constant_IV_size]	constant_IV;
	}
}
```

some additional comments/thoughts: 

1. We would not call this tech mature, but we support developing this further, the DASH-IF doc is relatively new and HLS RFC 8216 seems rather silent on this topic, e.g. requiring  EXT-X-DISCONTINUITY seems not explicitly recommended for this
2. To avoid ecosystem fragmentation I would initially recommend the signalling to exist both inband and in the manifest, this is a small criticism on the DASH-IF doc, by having 2 approaches fragmentation may happen. 
3. Also I would recommend explitly that changes in key only occur at segment boundaries (I beleive this is already assumed implicitly) but would be good to emphasize that  
4. It would also really help if CTA could be involved in developing test content and test cases for this, but that would be another group of CTA WAVE such as dpctf

**Comment by RufaelDev** [comment]
Another comment on this, the requests (in advance) for updated licenses/keys would need to be studied as well. This may not only apply to players retrieving licenses/keys in advance but also other parts of the chain, .e.g. packagers, encoders and servers to facilitate the CPIX key exchange in advance. Is there any time how long in advance the player should make a license or key request ?

**Comment by technogeek00** [comment]
## Summary Notes (05/04/2022)
### General
- Use case: Changing of the encryption key within a single CMAF track
- Two types with a total of three possible methods
- Full license Rotation
  - Complete default_KID change (maximized compatibility recommendation)
  - KID change via sample group description change (general recommendation)
- Root/Leaf License Rotation
  - Key hierarchy structures (not interoperable)
- Key rotation is restricted to the CMAF Segment level by HLS

### KID change via sample group descriptions
- New key provided in `seig` box in `sbgp` per segment or chunk that overrides the default `tenc` parameters
- Implementers indicate fairly broad compatibility for this
- DASH has no explicit signaling requirements
- HLS must place an `EXT-X-KEY` tag prior to the first segment with the new key
  - Open Question: Is `DISCONTINUITY` needed? (thought is no)
- PSSH options
  - If desired to place in manifest/playlist, would need to be placed at rotation point, in DASH this means period cut
  - If desired to place in segment, then no change to manifest/playlist, but would need to provide per segment

### `default_KID` change
- New init with changed `default_KID` in `tenc` provided
- Guaranteed compatibility, but may not be seamless
- DASH requires new period with new `default_KID` signaling
- HLS must place an `EXT-X-KEY` and `EXT-X-MAP` with DISCONTINUITY tag prior to first segment with new key

### Key hierarchy structures
- Mention method as note but state lack of interoperability due to DRM support.

**Comment by nicoweilelemental** [comment]
What is the next step to progress on "_EXT-X-DATERANGE can be utilized to forward signal key change in variants (common scheme would need to be defined for specification to recommend this method)_"? Does Apple want to suggest a preferable HLS signaling approach or should we build a proposal for it?

The equivalent signaling in DASH is likely an Early Available Period including AdaptationSet and ContentProtection elements.
