### ISSUE TITLE
Relax Low Latency Use Case consideration text

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#25]
The Low latency use-case overview provides the following consideration text:

> The content is intended to be presented to end users with an end-to-end system latency that is less than the duration of a target CMAF segment duration

Rufael and Will have both raised good points on this being too restrictive:
> Rufael: is this realistic ? DVB defined 3.5 seconds as a commercial requirement

> Will: I agree with Rufael. This is too tight. A 3s target latency with 2s segments is feasible. A better threshold might be 3 segment durations, as that is the HLS default that the client holds back before starting playback.

If this is raised is low-latency addressing still applicable to the client operation?

**Comment by afcrowe** [comment]
Agree with Will on matching HLS default of 3 segments:

> end-to-end system latency that is equal or less than 3 CMAF segment durations

**Comment by technogeek00** [comment]
Implemented in Draft 2
