### ISSUE TITLE
Relax constraint for cenc/cbcs components not sharing encryption keys

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#27]
The text currently provides the interoperability recommendation when generating cenc encrypted components:

>The cenc and cbcs components SHALL NOT share encryption keys

Is this too strict of a statement? Should it be relaxed to SHOULD NOT instead.

**Comment by RufaelDev** [comment]
I don't think it matters that much, people will perhaps not read this document to get advice on what security is appropriate for them, so perhaps adding a note to clarify that this relates to security and not interoperability between HLS and DASH may be the more helpful

**Comment by technogeek00** [comment]
Actually it was decided in a previous meeting to remove the `cenc` / `cbcs` security note and it was removed from the main authoring but not the DASH content constraints (https://github.com/cta-wave/dash-hls/issues/19#issuecomment-713644311). I've updated the document to remove it from the DASH constraints as well to align with previous agreements.
