### ISSUE TITLE
Section Reviewers

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#28]
Tracking the in group document and section review volunteers, if you would like to be added to a section please comment below.

# Full Document Reviewers

- John Simmons
- Krasimir Kolarov

# Section Reviewers

Section | Subsection | Reviewer(s)
---|---|---
Defining DASH-HLS Interoperability | 3.1 The CMAF Media Object Model | 
Defining DASH-HLS Interoperability | 3.2 The DASH CMAF Profile |  
Defining DASH-HLS Interoperability | 3.3 The HLS CMAF Profile | 
DASH and HLS Interoperability Use Cases | 4.1 Basic On-Demand and Live Streaming | Yasser Syed
DASH and HLS Interoperability Use Cases | 4.2 Low Latency Live Streaming | Yasser Syed, Will Law
DASH and HLS Interoperability Use Cases | 4.3 Encrypted Media Presentations | Yasser Syed
DASH and HLS Interoperability Use Cases | 4.4 Presentation Splicing | Yasser Syed
DASH-HLS Presentation Conversion Details | 5.1 Basic On-Demand and Live Streaming | 
DASH-HLS Presentation Conversion Details | 5.2 Low Latency Live Streaming | Will Law
DASH-HLS Presentation Conversion Details | 5.3 Encrypted Media Presentations | 
DASH-HLS Presentation Conversion Details | 5.4 Presentation Splicing |

**Comment by wilaw** [comment]
Here's the doc link so we all review the same thing https://hulu-my.sharepoint.com/:w:/p/zachary_cava/EbMtunUhSCdNhgncLjonHF4BTMSHLJbr0POBgNKwLl47rA?rtime=ggBXThbD2Eg

**Comment by technogeek00** [comment]
Review complete, thank you to additional individuals and groups that provided reviews of the entire document.
