### ISSUE TITLE
Single codec a multi-period adaptation set constraint for HLS-DASH Interop

### ISSUE THREAD

**Issue by johnsim** [cta-wave/dash-hls#3]
Annex D. CMAF Encoding for DASH-HLS Interoperability, Section D.4.3. Adaptation Set Constraints
States: The corresponding Adaptation Sets in two Periods SHALL have the same @id, content type, codec, peak bandwidth and language values. 

Is this required for HLS and DASH Interop?

**Comment by technogeek00** [comment]
Covered in splicing recommendations for the cross manifest/playlist transforms in first edition
