### ISSUE TITLE
Fall 2024 HLS Interest Group Meeting

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#54]
This issue is for capturing the interoperability issues between DASH and HLS that this group has identified for potential discussion in the 2024 HLS Interest Group meeting. Feel free to propose additional issues as comments to this issue and the group can review them. This description will be updated with issues as they are added.

Explicit note: no issues have been added so far.

**Comment by nicoweilelemental** [comment]
From Valentijn Siebrands (Unified Streaming) and the DASH-IF CPS working group:

During the last Dash-IF Content Protection WG call we discussed DRM Key Rotation interoperability inside the Dash realm but also the interoperability with HLS CMAF. 

One of the topics we discussed is if and how Apple HLS team looks at the mechanisms mentioned in chapter 9 of the DASH-IF IOP-6 V5.0.0 <https://dashif.org/docs/IOP-Guidelines/DASH-IF-IOP-Part6-v5.0.0.pdf> document. More in particular if the HLS team is willing to adopt / accept / consider / not-to-break when CMAF box structures as explained in 9.3 & 9.4 are presented to an Apple player.

A couple of Packager and DRM providers are currently re-visiting the keyrotation specifications and are discussing ways to avoid 'License request storms' by introducing alternative signalling (e.g. in-band, no new cmaf-header-init-per-rotate etc) and other License Acquisitioning models (N keys for the next Y periods).
