### ISSUE TITLE
Issue Migration

### ISSUE THREAD

**Issue by technogeek00** [cta-wave/dash-hls#9]
We need to pull over all DASH-HLS Interop issues from the CSTF tracker to centralize, can be found via this query: https://github.com/cta-wave/content-specification-task-force/issues?q=is%3Aissue+is%3Aopen+label%3ADASH-HLS-INTEROP

**Comment by technogeek00** [comment]
Two issue remain that I'd like confirmation should be pulled over:
- https://github.com/cta-wave/content-specification-task-force/issues/34
- https://github.com/cta-wave/content-specification-task-force/issues/37

I believe they should be homed here based on the conversation, but want to confirm. @johnsim ?

**Comment by johnsim** [comment]
I agree.
John

________________________________

**Comment by technogeek00** [comment]
Migrated!
